#nginx-mrigank-rc.yaml 
apiVersion: v1
kind: ReplicationController
metadata: 
  labels: 
    app: nginx-app
  name: nginx-mrigank-rc
spec: 
  replicas: 3
  selector: 
    app: nginx-app
  template: 
    metadata: 
      labels: 
        app: nginx-app
      name: nginx-pod
    spec: 
      containers: 
        - 
          image: nginx
          name: nginx-container
          ports: 
            - 
              containerPort: 6443
    
